version: '3.9'
services:

  challenge-java:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./task-api/target/task-api-1.1-SNAPSHOT.jar:/app.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb-challenge:27017/test
      - SPRING_DATA_REDIS_URL=redis://redis-challenge:6379
    depends_on:
      mongodb-challenge:
        condition: service_healthy
      redis-challenge:
        condition: service_healthy
    container_name: challenge-java

  mongodb-challenge:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-challenge
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  redis-challenge:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis-challenge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./0-monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    container_name: prometheus

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./0-monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana

volumes:
  prometheus-data:
  grafana-data:
